class_name ItemDef extends Resource

enum ItemId {
	ADD_STAMINA,
	SPEED_BUFF_ON_DESTROY,
	SPAWN_RANDOM_TILE_OBJECT,
	LEVEL_UP_ITEM_ON_TOUCH,
	SPAWN_BOUNCE_PILLAR,
	INCREASE_SIZE,
	BOUNCE_OFF_EVERYTHING,
	SNAIL_TRAIL_OF_LEVEL_UP_SLIME,
	SNAIL_TRAIL_OF_LEVEL_UP_SLIME_TIME_BASED,
	MORE_DAMAGE,
	SPAWN_CROPS_ON_START,
}

@export var item_id: ItemId

func _init(item_id: ItemId = ItemId.ADD_STAMINA):
	self.item_id = item_id
